### ISSUE TITLE
Demonstrating what the increased efficiency of this looks like in practie!

### ISSUE THREAD

**Issue by Trosterud** [sam-hosseini/dotfiles#1]
Would love to one day see an in depth demonstration of your workflow with this!

I know you've spent time and effort both setting up and learning how to use this, properly. 10x:ing your output and efficiency

Seeing a gif of it in action (f.ex a gif of the video you made in another repo for a string based task you did). And a 3 point "why" ( see React's https://github.com/facebook/react ) would really drive this point home for other developers

Best of luck and have a great week Sam

**Comment by sam-hosseini** [comment]
It's so nice to see friends commenting on on your work, makes github a much friendlier place 😄

You're asking a very good question to which I don't have an answer at the moment. When I started building this, I couldn't even imagine how it would make my productivity so much higher. And now that I know it by heart, I'm 100% sold on it that it's good for me.

However, to make others sold on it, it becomes my responsibility to showcase how much more effective people can become with such a thing. And since you and I are a fan of Nasim Taleb, we know that we should be able to measure something concretely to be able to anaylyse it, but how can you actually measure _productivity_? Tough one.

I still need to clear up my thinking about this, but what comes to mind now is that this kinda setup helps you in two ways:

- First is that you have a reference point for everything in your laptop.
    - You wanna add VLC application to your macOS? Add it to [Brewfile_cask](https://github.com/sam-hosseini/dotfiles/blob/master/brew/Brewfile_cask) and run the `bootstrap` function in your shell again.
    - You are tired of never remembering how to extract a file in terminal? Make a [`extract`](https://github.com/sam-hosseini/dotfiles/blob/master/fish/functions/extract.fish) function in your fish shell and you're done, just use it like `extract FILENAME`.
    - You wanna keep your packages (npm packages, pip packages, brew packages, etc etc) up to date? Make a [`up`](https://github.com/sam-hosseini/dotfiles/blob/master/fish/functions/up.fish) fish shell function and execute it every week or so.
   - And many many other things which you can see in the repo. Saved configs for `tmux`, `vim`, etc etc. You wanna change anything? Go to the file, make your changes, test if it works, commit and push. You are done. Your environment will ALWAYS behave consistently.

- Second is that you actually become faster in your navigation around your laptop and text editor and etc.
    - Wanna work on a Python project? Sure. Open a `tmux` environment with 4 `panes` (each pane is a terminal shell). In one of them, open `vim` and start editing there. In one of them, do `docker-compose up`, in one run your tests continuously with `pytest-watch` and in one, do normal commands and make git commands. Can you imagine how much more effective you'll be when you don't have to switch ALL THE TIME between 4 different `TABS` in a terminal, and you're just in a single `tab`, in a single tmux `window`, with just 4 `panes`?
    - Wanna quickly open an application? Sure. `cmd + space` opens Alfred search. Alfred search learns from your typings. So, if you tend to open `Sublime Text` for example a lot, all the keyboard buttons you have to press to open it is `cmd + space` + one `S` charachter which then makes sublime as the first search result + `enter`. Now you might tell me "but hey Mr. Genius 😄 , I can just go to my dock and click on Sublime" and you sure can. But once you have too many apps in your dock, and too many open apps, I'm rather certain it takes more time to move your mouse over to dock, find the place of Sublime by eye, and go and click on it. Compared to opening Alfred search, pressing S and enter. 
     - And many other small optimizations I've done over the last 2 years which is in `macOS` folder and also Karabiner. And these small optimizations, over time, makes you just ultra fast at doing all the normal things in your environment.

So, the _why_ part for me is that the more I spent time on this, the less I spent time afterwards. It's like investing in your physical fitness; the stronger you become, the less energy you'll have to spend lifting normal things up. I've spent probably around 600 hours on this repo, but in the last 2 years, I've setup ~5 new macbooks because of new jobs and laptops etc, and each of them took less than 2 hours. Normally, it would take 2 full working days. That's like ~60 hours saved, and who knows how much I save everyday by just operating faster. 

As you know, I'm into this subject a lot and will make a course at some point when I have the resources to teach others what I learned with this and to help them set this up in a step-by-step fashion. So hopefully then, I can have a more concise and coherent answer and chain of thoughts.

In the mean time, I wish you all the best my friend 🌷
